version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    environment:
      - REDIS_ARGS=--requirepass=mypassword
      - REDISINSIGHT_AUTH_PASSWORD=insightpassword
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./local-data:/data
    restart: unless-stopped
